title: Badr's Blog
description: > # this means to ignore newlines until "baseurl:"
  This is Badr's blog
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "http://bkhmsi.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Badr AlKhamissi # add your name
author-img: badr.jpg # add your photo
about-author: > 
  Hi there! Thank you for visiting my blog.
social-twitter: bkhmsi # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: bkhmsi # add your Github handle
social-linkedin: bkhmsi # add your Linkedin handle
social-email: badr@khamissi.com # add your Email address

# Disqus
discus-identifier: bkhmsi # add your discus identifier

# Tracker
analytics: UA-126373582-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
